# This workflow will install Python dependencies, run tests, code coverage, ...

name: Test Pull Requests

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - python-version: 3.6
            DISPLAY_NAME: "Singularity Tests"
            RUN_TESTS: true
            USE_SINGULARITY: true
          - python-version: 3.7
            DISPLAY_NAME: "Singularity Tests + CODECOV"
            RUN_TESTS: true
            USE_SINGULARITY: true
            RUN_CODECOV: true
          - python-version: 3.7
            DISPLAY_NAME: "Codestyle"
            RUN_CODESTYLE: true
          - python-version: 3.7
            DISPLAY_NAME: "Singularity Container Examples"
            RUN_CONTAINER_EXAMPLES: true
            USE_SINGULARITY: true
          - python-version: 3.7
            DISPLAY_NAME: "Local Examples"
            RUN_LOCAL_EXAMPLES: true
            USE_SINGULARITY: false
          - python-version: 3.8
            DISPLAY_NAME: "Singularity Tests"
            RUN_TESTS: true
            USE_SINGULARITY: true
          - python-version: 3.9
            DISPLAY_NAME: "Singularity Tests"
            RUN_TESTS: true
            USE_SINGULARITY: true
      fail-fast: false

    name: Tests ${{ matrix.python-version }} ${{ matrix.DISPLAY_NAME }}

    env:
      RUN_TESTS: ${{ matrix.RUN_TESTS }}
      USE_SINGULARITY: ${{ matrix.USE_SINGULARITY }}
      RUN_CODECOV: ${{ matrix.RUN_CODECOV }}
      RUN_CODESTYLE: ${{ matrix.RUN_CODESTYLE }}
      RUN_CONTAINER_EXAMPLES: ${{ matrix.RUN_CONTAINER_EXAMPLES }}
      RUN_LOCAL_EXAMPLES: ${{ matrix.RUN_LOCAL_EXAMPLES }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Go for Singularity
      if: matrix.USE_SINGULARITY == true
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.15' # The Go version to download (if necessary) and use.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        chmod +x ci_scripts/install.sh && source ./ci_scripts/install.sh
    - name: Run Tests
      run: chmod +x ci_scripts/script.sh && source ./ci_scripts/script.sh